import { parseProxyURI, decodeSubscriptionText, deduplicateConfigs, addFingerprints } from './parser.js';
import { quickProbe } from './quick-tester.js';
import { runPool } from './scheduler.js';
import { getSetting, setSetting, deleteSetting, getCachedResult, putCachedResult, addHistoryRun, getHistoryRuns } from './storage.js';

const DEFAULT_SOURCES = [
  { id:'shatak-trojan-us', name:'Trojan US', url:'https://raw.githubusercontent.com/ShatakVPN/ConfigForge-V2Ray/main/configs/us/trojan.txt', enabled:true },
  { id:'shatak-vless-us', name:'VLESS US', url:'https://raw.githubusercontent.com/ShatakVPN/ConfigForge-V2Ray/main/configs/us/vless.txt', enabled:true },
  { id:'shatak-hy2-us', name:'Hysteria2 US', url:'https://raw.githubusercontent.com/ShatakVPN/ConfigForge-V2Ray/main/configs/us/hysteria2.txt', enabled:true },
  { id:'super-sub', name:'Super Sub', url:'https://raw.githubusercontent.com/MatinGhanbari/v2ray-configs/main/subscriptions/v2ray/super-sub.txt', enabled:true },
  { id:'extractor-us', name:'Extractor US', url:'https://raw.githubusercontent.com/arshiacomplus/v2rayExtractor/main/loc/US%20%F0%9F%87%BA%F0%9F%87%B8.txt', enabled:true },
  { id:'direct-sub', name:'Direct Sub', url:'https://zood.link/Motasel_Ba_Hame_Chi', enabled:true }
];
const $ = id => document.getElementById(id);
const state = { sources:structuredClone(DEFAULT_SOURCES), servers:[], selected:new Set(), filter:'all', visible:[], abort:null, running:false, qr:[], qrIndex:0, sourceHealth:new Map() };
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fa = v => Number(v||0).toLocaleString('fa-IR');
let toastTimer;
function toast(text,icon='✓'){ $('toastIcon').textContent=icon; $('toastText').textContent=text; $('toastMessage').classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('toastMessage').classList.remove('show'),2800); }
function setLive(text,kind='ready'){ $('liveStatusText').textContent=text; const colors={ready:'#10b981',running:'#38bdf8',warn:'#f59e0b',error:'#f43f5e'}; const c=colors[kind]||colors.ready; $('liveStatusBadge').style.borderColor=`${c}66`; const d=$('liveStatusBadge').querySelector('.status-dot'); if(d)d.style.background=c; }
function backendUrl(){ return $('backendUrlInput').value.trim().replace(/\/+$/,''); }
function headers(extra={}){ const t=$('backendTokenInput').value.trim(); return t?{...extra,Authorization:`Bearer ${t}`} : extra; }

async function persistSources(){
  const ok=$('persistSourcesToggle').checked;
  await setSetting('persist-sources',ok);
  if(ok) await setSetting('sources',state.sources.map(({id,name,url,enabled})=>({id,name,url,enabled})));
  else await deleteSetting('sources');
}
function renderSources(){
  $('sourcesWrapper').innerHTML=state.sources.map((s,i)=>{ const h=state.sourceHealth.get(s.id); const meta=!h?'—':h.ok?`${fa(h.valid)} valid / ${fa(h.raw)} raw`:'Fetch failed'; return `<div class="source-row" data-i="${i}"><input class="source-enabled" type="checkbox" ${s.enabled?'checked':''}><div><input class="source-name" type="text" value="${esc(s.name)}"><span class="source-meta ${h?.ok?'source-health-ok':h?'source-health-bad':''}">${esc(meta)}</span></div><input class="source-url" type="url" dir="ltr" value="${esc(s.url)}" placeholder="https://…"><button class="icon-btn source-delete" type="button">✕</button></div>`; }).join('');
  $('sourcesWrapper').querySelectorAll('.source-row').forEach(row=>{ const i=Number(row.dataset.i); const s=state.sources[i];
    row.querySelector('.source-enabled').onchange=e=>{s.enabled=e.target.checked; renderSourceCount(); persistSources();};
    row.querySelector('.source-name').onchange=e=>{s.name=e.target.value.trim()||`Sub ${i+1}`; persistSources();};
    row.querySelector('.source-url').onchange=e=>{s.url=e.target.value.trim(); state.sourceHealth.delete(s.id); persistSources();};
    row.querySelector('.source-delete').onclick=()=>{ if(state.sources.length<=1)return toast('حداقل یک منبع لازم است','⚠️'); state.sourceHealth.delete(s.id); state.sources.splice(i,1); renderSources(); persistSources(); };
  }); renderSourceCount();
}
function renderSourceCount(){ $('activeSourcesCountBadge').textContent=`${fa(state.sources.filter(s=>s.enabled&&s.url).length)} منبع فعال`; }
async function directFetch(url,signal){ const r=await fetch(url,{cache:'no-store',credentials:'omit',redirect:'follow',signal}); if(!r.ok)throw new Error(`HTTP ${r.status}`); return r.text(); }
async function backendFetch(url,signal){ const base=backendUrl(); if(!base)throw new Error('Backend تنظیم نشده'); const r=await fetch(`${base}/api/subscription?url=${encodeURIComponent(url)}`,{headers:headers({Accept:'text/plain'}),signal,cache:'no-store',credentials:'omit'}); if(!r.ok)throw new Error(`Backend ${r.status}`); return r.text(); }
async function loadConfigs(signal){
  const enabled=state.sources.filter(s=>s.enabled&&s.url.trim()); if(!enabled.length)throw new Error('منبع فعالی وجود ندارد'); updateProgress(2,'دریافت سابسکریپشن‌ها…'); const all=[];
  await Promise.all(enabled.map(async s=>{ try{ let text,via='direct'; try{text=await directFetch(s.url,signal);}catch(e){if(signal.aborted||!backendUrl())throw e; text=await backendFetch(s.url,signal); via='backend';} const lines=decodeSubscriptionText(text); const parsed=lines.map(parseProxyURI).filter(Boolean).map(c=>({...c,sourceId:s.id,sourceName:s.name})); state.sourceHealth.set(s.id,{ok:true,raw:lines.length,valid:parsed.length,via}); all.push(...parsed); }catch(e){state.sourceHealth.set(s.id,{ok:false,raw:0,valid:0,reason:e?.message||'Fetch failed'});} }));
  renderSources(); const unique=deduplicateConfigs(all); if(!unique.length)throw new Error('کانفیگ معتبری دریافت نشد؛ CORS یا لینک منابع را بررسی کنید'); return addFingerprints(unique);
}
function setRunning(v){ state.running=v; ['quickScanButton','realTestButton','checkBackendButton'].forEach(id=>$(id).disabled=v); $('stopTestButton').classList.toggle('hidden',!v); if(v)$('progressSection').classList.remove('hidden'); }
function updateProgress(p,label,m={}){ $('progressSection').classList.remove('hidden'); $('progressFillBar').style.width=`${Math.max(0,Math.min(100,p))}%`; $('progressPercentLabel').textContent=`${Math.round(p)}%`; $('progressStatusLabel').textContent=label; $('chipActiveConn').textContent=fa(m.active||0); $('chipSpeedRate').textContent=Number(m.rate||0).toFixed(1); $('chipEtaTime').textContent=m.etaSec==null?'—':`${m.etaSec}s`; }
function applyResult(s,r){ Object.assign(s,{status:r.status||'failed',latency:r.latency??null,reason:r.reason||'',probeType:r.probeType||'',testedAt:r.testedAt||Date.now(),score:r.score??null,verification:r.verification||null}); }
async function finishRun(mode,startedAt,aborted=false){ updateStats(); renderServers(); updateExport(); if(!aborted){const counts=countStatuses(); await addHistoryRun({mode,startedAt,finishedAt:Date.now(),total:state.servers.length,...counts}); await renderHistory();} setRunning(false); setLive(aborted?'متوقف شد':'تکمیل شد',aborted?'warn':'ready'); }
function countStatuses(){ return {verified:state.servers.filter(s=>s.status==='verified').length,reachable:state.servers.filter(s=>s.status==='reachable').length,uncertain:state.servers.filter(s=>s.status==='uncertain').length,failed:state.servers.filter(s=>s.status==='failed').length}; }
async function runQuick(){
  if(state.running)return; const c=new AbortController(); state.abort=c; setRunning(true); setLive('Quick Scan…','running'); const startedAt=Date.now();
  try{ state.selected.clear(); state.servers=await loadConfigs(c.signal); renderAll(); const timeout=Number($('timeoutConfigSelect').value||3500), concurrency=Number($('concurrencyConfigSelect').value||16);
    await runPool(state.servers,async s=>{const cached=await getCachedResult(s.fingerprintId); if(cached)return cached; const r=await quickProbe(s,timeout,c.signal); await putCachedResult(s.fingerprintId,r); return r;},{concurrency,signal:c.signal,onProgress:x=>{applyResult(x.item,x.result); updateProgress(8+(x.completed/x.total)*92,`${fa(x.completed)} از ${fa(x.total)}`,x); if(x.completed%8===0||x.completed===x.total){updateStats();renderServers();}}});
    await finishRun('quick',startedAt,c.signal.aborted);
  }catch(e){setRunning(false);setLive('خطا','error');toast(e?.message||'خطا در Quick Scan','❌');}
}
async function runReal(){
  if(state.running)return; if(!backendUrl())return toast('ابتدا Backend URL را وارد کنید','⚠️'); const c=new AbortController(); state.abort=c; setRunning(true);setLive('Real Verify…','running');const startedAt=Date.now();
  try{state.selected.clear();state.servers=await loadConfigs(c.signal);renderAll();const chunks=[];for(let i=0;i<state.servers.length;i+=20)chunks.push(state.servers.slice(i,i+20));let done=0;
    for(const chunk of chunks){ if(c.signal.aborted)break; const r=await fetch(`${backendUrl()}/api/verify`,{method:'POST',headers:headers({'Content-Type':'application/json'}),body:JSON.stringify({attempts:3,throughput:true,configs:chunk.map(s=>({fingerprintId:s.fingerprintId,raw:s.raw}))}),signal:c.signal,credentials:'omit',cache:'no-store'}); if(!r.ok)throw new Error(`Backend ${r.status}`); const data=await r.json(); for(const out of data.results||[]){const s=state.servers.find(x=>x.fingerprintId===out.fingerprintId);if(s){applyResult(s,out);await putCachedResult(s.fingerprintId,out);}} done+=chunk.length; updateProgress((done/state.servers.length)*100,`${fa(done)} از ${fa(state.servers.length)}`,{active:Math.min(20,chunk.length),rate:0,etaSec:null}); updateStats();renderServers(); }
    await finishRun('real',startedAt,c.signal.aborted);
  }catch(e){setRunning(false);setLive('خطا','error');toast(e?.name==='AbortError'?'تست متوقف شد':(e?.message||'خطای Real Verify'),'❌');}
}
async function checkBackend(){ if(!backendUrl())return toast('Backend URL خالی است','⚠️'); try{setLive('بررسی Backend…','running');const r=await fetch(`${backendUrl()}/health`,{cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error('Backend آماده نیست');setLive('Backend آماده','ready');toast(`sing-box ${d.singBoxVersion||''} آماده است`,'✅');}catch(e){setLive('Backend در دسترس نیست','error');toast(e?.message||'Backend در دسترس نیست','❌');} }

function statusRank(s){return ({verified:0,reachable:1,uncertain:2,pending:3,failed:4})[s]??5;}
function filteredServers(){const q=$('searchFilterInput').value.trim().toLowerCase();let a=state.servers.filter(s=>{const f=state.filter;if(['verified','reachable','uncertain','failed'].includes(f)&&s.status!==f)return false;if(['vless','trojan','vmess','hysteria2','ss'].includes(f)&&s.protocol!==f)return false;return !q||`${s.address} ${s.sni} ${s.tag} ${s.protocol} ${s.port}`.toLowerCase().includes(q);});const sort=$('sortOrderSelect').value;a.sort((x,y)=>sort==='status'?statusRank(x.status)-statusRank(y.status):sort==='protocol'?x.protocol.localeCompare(y.protocol):sort==='address'?x.address.localeCompare(y.address):(x.latency??999999)-(y.latency??999999));return a;}
function resultText(s){ if(s.status==='verified')return [`Verified${s.score!=null?` ${s.score}/100`:''}`,'result-verified']; if(s.status==='reachable')return [`${s.latency??'—'} ms`,'result-reachable']; if(s.status==='uncertain')return ['Uncertain','result-uncertain']; if(s.status==='failed')return ['Failed','result-failed']; return ['Pending','']; }
function renderServers(){const list=filteredServers();state.visible=list.map(s=>s.fingerprintId);if(!state.servers.length){$('serversListContainer').innerHTML='<div class="empty-state"><div>🚀</div><p>برای شروع Quick Scan یا Real Verify را بزنید.</p></div>';return;}if(!list.length){$('serversListContainer').innerHTML='<div class="empty-state"><p>نتیجه‌ای مطابق فیلتر نیست.</p></div>';return;}
  $('serversListContainer').innerHTML=list.map((s,i)=>{const [rt,rc]=resultText(s);return `<article class="server-card ${state.selected.has(s.fingerprintId)?'selected':''}" data-id="${esc(s.fingerprintId)}"><input class="server-check" type="checkbox" ${state.selected.has(s.fingerprintId)?'checked':''}><div class="rank">${i+1}</div><div class="server-main"><div class="server-title">${esc(s.address)}:${esc(s.port)} — ${esc(s.sni||s.tag||'')}</div><div class="server-tags"><span class="tag">${esc(s.protocol.toUpperCase())}</span><span class="tag">${esc(s.transport)}</span>${s.sourceName?`<span class="tag">${esc(s.sourceName)}</span>`:''}</div><div class="reason" title="${esc(s.reason)}">${esc(s.reason)}</div></div><div class="server-result"><strong class="${rc}">${esc(rt)}</strong><small>${esc(s.probeType||'')}</small></div><div class="server-actions"><button class="icon-btn copy-one">📋</button><button class="icon-btn qr-one">▦</button></div></article>`;}).join('');
  $('serversListContainer').querySelectorAll('.server-card').forEach(card=>{const s=state.servers.find(x=>x.fingerprintId===card.dataset.id);const toggle=()=>{state.selected.has(s.fingerprintId)?state.selected.delete(s.fingerprintId):state.selected.add(s.fingerprintId);renderServers();renderSelection();updateExport();}; card.querySelector('.server-check').onchange=toggle;card.onclick=e=>{if(!e.target.closest('button,input'))toggle();};card.querySelector('.copy-one').onclick=e=>{e.stopPropagation();copyText(s.raw,'کانفیگ کپی شد');};card.querySelector('.qr-one').onclick=e=>{e.stopPropagation();openQr([s.raw]);};});
}
function updateStats(){const c=countStatuses();$('statTotalCount').textContent=fa(state.servers.length);$('statVerifiedCount').textContent=fa(c.verified);$('statReachableCount').textContent=fa(c.reachable);$('statUncertainCount').textContent=fa(c.uncertain);$('statDeadCount').textContent=fa(c.failed);const lat=state.servers.map(s=>s.latency).filter(Number.isFinite);$('statBestLatency').textContent=lat.length?`${Math.min(...lat)}ms`:'—';}
function exportServers(){const m=$('exportModeSelect').value;if(m==='selected')return state.servers.filter(s=>state.selected.has(s.fingerprintId));if(m==='usable')return state.servers.filter(s=>['verified','reachable'].includes(s.status));return state.servers.filter(s=>s.status==='verified');}
function updateExport(){const a=exportServers();$('exportTextarea').value=a.map(s=>s.raw).join('\n');$('exportCountBadge').textContent=`${fa(a.length)} کانفیگ`;$('exportCardSection').classList.toggle('hidden',state.servers.length===0);}
function renderSelection(){const n=state.selected.size;$('selectionToolbar').classList.toggle('hidden',!n);$('selectedCountText').textContent=`${fa(n)} انتخاب`;}
function renderAll(){updateStats();renderServers();renderSelection();updateExport();}

async function copyText(text,msg='کپی شد'){if(!text)return;try{await navigator.clipboard.writeText(text);}catch{const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove();}toast(msg,'📋');}
function downloadText(text,name){if(!text)return;const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function b64(text){const bytes=new TextEncoder().encode(text);let bin='';for(const x of bytes)bin+=String.fromCharCode(x);return btoa(bin);}
function openModal(id){$(id).classList.add('open');}function closeModal(id){$(id).classList.remove('open');}
function openQr(items){if(window.__QR_VENDOR_MISSING__||typeof window.QRCode!=='function')return toast('کتابخانه QR محلی در دسترس نیست','❌');state.qr=items.filter(Boolean).slice(0,30);state.qrIndex=0;if(!state.qr.length)return toast('کانفیگی برای QR نیست','⚠️');renderQr();openModal('qrModalBackdrop');}
function renderQr(){const raw=state.qr[state.qrIndex],t=$('qrRenderTarget');t.innerHTML='';try{new window.QRCode(t,{text:raw,width:280,height:280,colorDark:'#000000',colorLight:'#ffffff',correctLevel:window.QRCode.CorrectLevel.L});}catch{$('qrLocalStatus').textContent='این کانفیگ برای QR بیش از حد طولانی است.';} $('qrRawText').textContent=raw;$('qrModalTitle').textContent=`QR محلی — ${fa(state.qrIndex+1)} از ${fa(state.qr.length)}`;$('qrCarouselNav').innerHTML=state.qr.length>1?'<button class="btn btn-ghost" id="qrPrev">قبلی</button><button class="btn btn-ghost" id="qrNext">بعدی</button>':'';$('qrPrev')?.addEventListener('click',()=>{state.qrIndex=Math.max(0,state.qrIndex-1);renderQr();});$('qrNext')?.addEventListener('click',()=>{state.qrIndex=Math.min(state.qr.length-1,state.qrIndex+1);renderQr();});}
function downloadQr(){const t=$('qrRenderTarget'),canvas=t.querySelector('canvas'),img=t.querySelector('img');const href=canvas?.toDataURL('image/png')||img?.src;if(!href)return toast('QR قابل دانلود نیست','⚠️');const a=document.createElement('a');a.href=href;a.download=`proxy-qr-${state.qrIndex+1}.png`;a.click();}
async function renderHistory(){const rows=await getHistoryRuns(20);$('historyList').innerHTML=rows.length?rows.map(r=>`<div class="history-item"><strong>${new Date(r.startedAt).toLocaleString('fa-IR')}</strong><span>${r.mode==='real'?'Real Verify':'Quick Scan'}</span><span>${fa(r.total)} کل</span><span>✅ ${fa(r.verified||0)} / 🟢 ${fa(r.reachable||0)}</span><span>🔴 ${fa(r.failed||0)}</span></div>`).join(''):'<div class="empty-inline">هنوز تستی ثبت نشده است.</div>';}

async function init(){
  const persist=await getSetting('persist-sources',false);$('persistSourcesToggle').checked=Boolean(persist);if(persist){const saved=await getSetting('sources',null);if(Array.isArray(saved)&&saved.length)state.sources=saved;}const bu=await getSetting('backend-url','');if(bu)$('backendUrlInput').value=bu;renderSources();renderAll();renderHistory();
  $('addSourceButton').onclick=()=>{state.sources.push({id:`custom-${Date.now()}`,name:`Sub ${state.sources.length+1}`,url:'',enabled:true});renderSources();persistSources();};
  $('persistSourcesToggle').onchange=persistSources;$('backendUrlInput').onchange=()=>setSetting('backend-url',backendUrl());$('quickScanButton').onclick=runQuick;$('realTestButton').onclick=runReal;$('stopTestButton').onclick=()=>state.abort?.abort();$('checkBackendButton').onclick=checkBackend;
  $('searchFilterInput').oninput=renderServers;$('sortOrderSelect').onchange=renderServers;$('exportModeSelect').onchange=updateExport;$('filterPills').onclick=e=>{const b=e.target.closest('.pill');if(!b)return;state.filter=b.dataset.filter||'all';document.querySelectorAll('.pill').forEach(x=>x.classList.toggle('active',x===b));renderServers();};
  $('selectVisibleButton').onclick=()=>{state.visible.forEach(id=>state.selected.add(id));renderServers();renderSelection();updateExport();};$('selectUsableButton').onclick=()=>{state.servers.filter(s=>['verified','reachable'].includes(s.status)).forEach(s=>state.selected.add(s.fingerprintId));renderAll();};$('clearSelectionButton').onclick=()=>{state.selected.clear();renderAll();};$('copySelectedButton').onclick=()=>copyText(state.servers.filter(s=>state.selected.has(s.fingerprintId)).map(s=>s.raw).join('\n'),'انتخاب‌ها کپی شد');$('qrSelectedButton').onclick=()=>openQr(state.servers.filter(s=>state.selected.has(s.fingerprintId)).map(s=>s.raw));
  $('copyExportButton').onclick=()=>copyText($('exportTextarea').value,'خروجی کپی شد');$('downloadExportButton').onclick=()=>downloadText($('exportTextarea').value,`trojan-tester-${new Date().toISOString().slice(0,10)}.txt`);$('qrExportButton').onclick=()=>openQr(exportServers().map(s=>s.raw));$('base64ExportButton').onclick=()=>{$('base64Output').textContent=b64($('exportTextarea').value);openModal('base64ModalBackdrop');};$('webShareButton').onclick=async()=>{const text=$('exportTextarea').value;if(!text)return;if(navigator.share){try{await navigator.share({title:'Proxy configs',text});}catch{}}else copyText(text);};$('copyBase64Button').onclick=()=>copyText($('base64Output').textContent,'Base64 کپی شد');$('copyQrConfigButton').onclick=()=>copyText(state.qr[state.qrIndex]||'','کانفیگ QR کپی شد');$('downloadQrButton').onclick=downloadQr;$('refreshHistoryButton').onclick=renderHistory;
  document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>closeModal(b.dataset.closeModal));document.querySelectorAll('.modal-backdrop').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id);});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal-backdrop.open').forEach(m=>closeModal(m.id));});
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
}
document.addEventListener('DOMContentLoaded',init);
